### ISSUE TITLE
An error occurred: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Restwing-droid** [Runware/sdk-python#11]
`import asyncio
import os
import logging
from typing import List, Optional
from dotenv import load_dotenv
from runware import Runware, IImageInference

# Load environment variables from .env file
load_dotenv()

RUNWARE_API_KEY = os.environ.get("RUNWARE_API_KEY")

async def main() -> None:
  runware = Runware(api_key=RUNWARE_API_KEY)

  try:
      await runware.connect()
      print("Successfully connected to Runware.")  # Add this line
  except Exception as e:
      print(f"Error connecting to Runware: {e}")
      return  # Exit if connection fails

  request_image = IImageInference(
    positivePrompt="a beautiful sunset over the mountains",
    model="civitai:25694@143906",
    numberResults=4,
    negativePrompt="cloudy, rainy",
    useCache=False,
    height=512,
    width=512,
    outputFormat="PNG",
  )

  try:
      images = await runware.imageInference(requestImage=request_image)
      print(f"Raw API Response: {images}")  # Add for debugging
      if images is not None:
          for image in images:
              print(f"Image URL: {image.imageURL}")
      else:
          print("Error: No images returned from the API. Check your API key, model ID, and network connection.")
  except Exception as e:
      print(f"An error occurred: {e}")

if __name__ == "__main__":
    asyncio.run(main())`

I am able to sucessfully connect to runware, but after a considerable wait, I get the error message "An error occurred: argument of type 'NoneType' is not iterable".

I can see in my "Usage" panel the requests are being recognised and even saying images have been generated. It seems that any model from civitai creates this error. When I use `runware:100@1` it does work as expected.

Many thanks.

**Comment by Restwing-droid** [comment]
Actually, I can only create 1024x1024 images using `runware:100@1` I get a Nonetype error if I change it to anything else (divisible by 8)

**Comment by Restwing-droid** [comment]
I get these `Nonetype errors` randomly. One time the same python script will work, another time it will not. The account is charged regardless of whether or not I get the error... Hope you work out a solution.

**Comment by konkey** [comment]
I'm also experiencing this issue regardless of the settings or model used. It seems like sometimes the API will just time out and return this error, even in the middle of a batch request.

```
Sending image inference request...
Received 1 partial images
Partial Image URL: ***
Received 1 partial images
Partial Image URL: ***
An error occurred: argument of type 'NoneType' is not iterable
```

**Comment by felixsanz** [comment]
Can you please try again? And also try a custom Stable Diffusion model from Civitai, instead of a custom FLUX model, in case that's the issue. We've been fixing some bugs this last two days so maybe this is already fixed, let me know

**Comment by Restwing-droid** [comment]
Thanks, I've done a `pip install runware -U` but I was up to date.
I've tried with `runware:101@1` as well as the original FluxDev from CivitAI `urn:air:flux1:checkpoint:civitai:618692@691639`.
I've tried with SDXL checkpoints and the problem is unpredictable. I can send a request and get a Nonetype error, not change anything and try again and it will work. Unfortuantely, it only works roughly 1 out of 6 tries (however credit is deducted from the wallet in my account) This is the same regardless of model being used.
When it works, the speed is absolutely fantastic! So I really hope you can iron out the bugs.

**Comment by gokturkDev** [comment]
I think I am getting a derivative of this error as well

```
<class 'TypeError'>
'NoneType' object is not subscriptable
```


> I get these `Nonetype errors` randomly. One time the same python script will work, another time it will not. The account is charged regardless of whether or not I get the error... Hope you work out a solution.

Is the same for as well. I am using a retry mechanism to with backoff but its introducing considerable latency to the program.
I am using the latest version. 
Would you mind taking a second look at this? 
@felixsanz

**Comment by arcanite24** [comment]
Hi!

We're also getting the same error. We're getting it on random scenarios, mainly when batch_size > 1

cc: @Astropulse

**Comment by gokturkDev** [comment]
hey this is happening quite often and this issue is open for months now.
look you are not aws and you don't have to have 100% uptime but at least tell us why this is happening

**Comment by bghira** [comment]
@gokturkDev hello! we experienced a datacentre outage this morning. if you are experiencing this issue, please open a new issue report with debug logs and request details. this issue is distinct, as it had a resolution put in during the v0.3.x release cycles. any new similar issues would have their own root cause, and tracking it in this issue confuses two problems.
