### ISSUE TITLE
cannot import name 'IRequestImage' from 'runware'

### ISSUE THREAD

**Issue by mrthevinh** [Runware/sdk-python#3]
`Traceback (most recent call last):
  File "E:\editvideo\runimage.py", line 1, in <module>
    from runware import Runware, IRequestImage
ImportError: cannot import name 'IRequestImage' from 'runware' (E:\editvideo\.conda\lib\site-packages\runware\__init__.py)`

**Comment by felixsanz** [comment]
Can you try with `IImageInference` ? I think it got renamed in the last update

**Comment by mrthevinh** [comment]
> Can you try with `IImageInference` ? I think it got renamed in the last update

Thank you!
