### ISSUE TITLE
720x1280 - Invalid value for width parameter. Image width must be an integer value between 512 and 2048, in multiples of 4.

### ISSUE THREAD

**Issue by mrthevinh** [Runware/sdk-python#4]
720/4=180
`RUNWARE_API_KEY = os.environ.get("RUNWARE_API_KEY")

async def request_single_image(prompt, model,  width=720, height=1280):
    # Create an instance of Runware
    runware = Runware(api_key=RUNWARE_API_KEY)

    # Connect to the Runware service
    await runware.connect()

    # Define the image inference request
    request_image = IImageInference(
        positivePrompt=prompt,
        model=model,
        numberResults=1,
        height=height,
        width=width,
        includeCost=True
    )

    # Send the request and handle exceptions
    try:
        images = await runware.imageInference(requestImage=request_image)
        if images:
            for image in images:
                print(f"Image URL: {image.imageURL}")
        else:
            print("No images generated.")
    except RunwareAPIError as e:
        print(f"API Error: {e}")
    except Exception as e:
        print(f"Unexpected Error: {e}")`

**Comment by felixsanz** [comment]
Can you please try again? It should be fixed.

**Comment by mrthevinh** [comment]
> Can you try a multiple of 64 for now? We'll deploy a fix tomorrow to make it a multiple of 8.

Thank you! work with 512x896
