### ISSUE TITLE
outputType & outputFormat are not working.

### ISSUE THREAD

**Issue by ramphy** [Runware/sdk-python#5]
Response:
[IImage(taskType='imageInference', imageUUID='591051d7-7340-45c3-bc82-966787c51806', taskUUID='6ff68fb8-dd5c-4da4-a943-b3ad5ca8d443', inputImageUUID=None, imageURL='https://im.runware.ai/image/ws/0.5/ii/591051d7-7340-45c3-bc82-966787c51806.jpg', imageBase64Data=None, imageDataURI=None, NSFWContent=False, cost=None)]

I'm trying to use outputType & outputFormat.

**Comment by felixsanz** [comment]
Hi @ramphy, can you please share the snippet of code you're using to make the request?

`outputType` accepts `base64Data`, `dataURI` or `URL` values. Default is `URL`, so that will include `imageURL='https://...'` in the response.

`outputFormat` accepts `JPG`, `PNG` or `WEBP`. Default is `JPG`.

**Comment by ramphy** [comment]
`import os
from dotenv import load_dotenv
load_dotenv()
RUNWARE_API_KEY = os.environ.get("RUNWARE_API_KEY")
from flask import Flask, request, jsonify
from runware import Runware, IImageInference
import asyncio
import websockets

app = Flask(__name__)

async def generate_images(positive_prompt, negative_prompt, model, number_results, height, width, outputType, outputFormat):
    runware = Runware(api_key=RUNWARE_API_KEY)
    try:
        await runware.connect()
    except asyncio.TimeoutError as e:
        return {'error': 'TimeoutError', 'message': str(e)}

    request_image = IImageInference(
        positivePrompt=positive_prompt,
        model=model,
        numberResults=number_results,
        negativePrompt=negative_prompt,
        useCache=False,
        height=height,
        width=width,
        outputType=outputType,
        outputFormat=outputFormat,
    )

    try:
        images = await runware.imageInference(requestImage=request_image)
    except Exception as e:
        return {'error': 'InferenceError', 'message': str(e)}

    return images

@app.route('/generate-images', methods=['POST'])
def generate_images_endpoint():
    data = request.json
    positive_prompt = data.get('positivePrompt', 'a beautiful sunset over the mountains')
    negative_prompt = data.get('negativePrompt', 'cloudy, rainy')
    model = data.get('model', 'civitai:36520@76907')
    number_results = data.get('numberResults', 4)
    height = data.get('height', 512)
    width = data.get('width', 512)
    outputType = data.get('outputType', 'dataURI')
    outputFormat = data.get('outputFormat', 'WEBP')
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    images = loop.run_until_complete(generate_images(positive_prompt, negative_prompt, model, number_results, height, width, outputType, outputFormat))
    print(images)
    if 'error' in images:
        return jsonify(images), 500

    image_urls = [image.imageURL for image in images]
    return jsonify({'imageURLs': image_urls})

if __name__ == '__main__':
    app.debug = True
    app.run(host='0.0.0.0', port=5000)
`

**Comment by andreidavid** [comment]
Hi @ramphy, thank you for the bug report. Should be fixed now in version v0.2.1 :)

**Comment by ramphy** [comment]
> Hi @ramphy, thank you for the bug report. Should be fixed now in version v0.2.1 :)

thank to you.
